# Generated by Django 6.1.1 on 2026-09-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Ej: 'temperature'", unique=True)),
                ('name', models.CharField(help_text="Ej: 'Temperatura'", max_length=100)),
                ('default_unit', models.CharField(help_text="Ej: '°C', '%', 'ppm'", max_length=20)),
                ('valid_min', models.FloatField(blank=True, null=True)),
                ('valid_max', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('api_key_hash', models.CharField(editable=False, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='greenhouses.greenhouse')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, help_text='Si se deja vacío, se usa la unidad por defecto del tipo de sensor.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reading_interval_seconds', models.PositiveIntegerField(default=60, help_text='Cada cuántos segundos se espera una lectura de este sensor.')),
                ('persist_interval_seconds', models.PositiveIntegerField(blank=True, help_text='Guardar como máximo 1 lectura cada N segundos. Vacío = nunca guardar (solo tiempo real). 0 = guardar todo.', null=True)),
                ('persist_deadband', models.FloatField(blank=True, help_text='Guardar también si el valor cambia al menos esto desde el último guardado.', null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.device')),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='greenhouses.greenhouse')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='greenhouses.zone')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='sensors.sensortype')),
            ],
            options={
                'ordering': ['greenhouse', 'name'],
            },
        ),
    ]
