# Generated by Django 6.1.1 on 2026-10-01 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("greenhouses", "0001_initial"),
        ("sensors", "0002_sensortype_greenhouse_alter_sensortype_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("high", "Por encima del máximo"),
                            ("low", "Por debajo del mínimo"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Aviso"), ("critical", "Crítica")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activa"), ("resolved", "Resuelta")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("threshold", models.FloatField(help_text="El límite que se cruzó.")),
                (
                    "trigger_value",
                    models.FloatField(help_text="Valor que abrió la alerta."),
                ),
                (
                    "peak_value",
                    models.FloatField(
                        help_text="Valor más extremo mientras estuvo abierta."
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "greenhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="greenhouses.greenhouse",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="sensors.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Opcional; si se deja vacío se genera uno.",
                        max_length=100,
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True,
                        help_text="Alerta si el valor baja de este número.",
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True,
                        help_text="Alerta si el valor supera este número.",
                        null=True,
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Aviso"), ("critical", "Crítica")],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notify_email", models.BooleanField(default=True)),
                (
                    "breach_since",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "active_alert",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="alerts.alert",
                    ),
                ),
                (
                    "greenhouse",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="greenhouses.greenhouse",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="sensors.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["sensor_id", "id"],
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="alerts.alertrule",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_value__isnull", False),
                    ("max_value__isnull", False),
                    _connector="OR",
                ),
                name="alertrule_has_a_limit",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["greenhouse", "status", "-opened_at"],
                name="alert_gh_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["sensor", "-opened_at"], name="alert_sensor_idx"
            ),
        ),
    ]
