# Generated by Django 6.1.1 on 2026-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        ("greenhouses", "0001_initial"),
        ("sensors", "0002_sensortype_greenhouse_alter_sensortype_code_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="alertrule",
            name="alertrule_has_a_limit",
        ),
        migrations.AddField(
            model_name="alertrule",
            name="rule_type",
            field=models.CharField(
                choices=[("threshold", "Fuera de límites"), ("no_signal", "Sin señal")],
                default="threshold",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="kind",
            field=models.CharField(
                choices=[
                    ("high", "Por encima del máximo"),
                    ("low", "Por debajo del mínimo"),
                    ("stale", "Sin señal"),
                ],
                max_length=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rule_type", "no_signal"),
                    ("min_value__isnull", False),
                    ("max_value__isnull", False),
                    _connector="OR",
                ),
                name="alertrule_has_a_limit",
            ),
        ),
    ]
