--
-- PostgreSQL database dump
--

\restrict k5Enqu4KJgkXm7p9RU1NhmhGI8aoMTRig5rw8U3CwMtsyPp2GgKbNvUIKl5hjXE

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actuators_actuator; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.actuators_actuator (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    state boolean NOT NULL,
    config jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    device_id bigint,
    greenhouse_id bigint NOT NULL,
    zone_id bigint,
    actuator_type_id bigint NOT NULL
);


ALTER TABLE public.actuators_actuator OWNER TO invernadero;

--
-- Name: actuators_actuator_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.actuators_actuator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actuators_actuator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actuators_actuatorstatehistory; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.actuators_actuatorstatehistory (
    id bigint NOT NULL,
    state boolean NOT NULL,
    source character varying(20) NOT NULL,
    changed_at timestamp with time zone NOT NULL,
    actuator_id bigint NOT NULL,
    changed_by_id bigint
);


ALTER TABLE public.actuators_actuatorstatehistory OWNER TO invernadero;

--
-- Name: actuators_actuatorstatehistory_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.actuators_actuatorstatehistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actuators_actuatorstatehistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actuators_actuatortype; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.actuators_actuatortype (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    greenhouse_id bigint
);


ALTER TABLE public.actuators_actuatortype OWNER TO invernadero;

--
-- Name: actuators_actuatortype_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.actuators_actuatortype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actuators_actuatortype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO invernadero;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO invernadero;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO invernadero;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO invernadero;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO invernadero;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO invernadero;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO invernadero;

--
-- Name: greenhouses_greenhouse; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.greenhouses_greenhouse (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    timezone character varying(64) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.greenhouses_greenhouse OWNER TO invernadero;

--
-- Name: greenhouses_greenhouse_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.greenhouses_greenhouse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.greenhouses_greenhouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: greenhouses_zone; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.greenhouses_zone (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    greenhouse_id bigint NOT NULL
);


ALTER TABLE public.greenhouses_zone OWNER TO invernadero;

--
-- Name: greenhouses_zone_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.greenhouses_zone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.greenhouses_zone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memberships_membership; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.memberships_membership (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    greenhouse_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.memberships_membership OWNER TO invernadero;

--
-- Name: memberships_membership_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.memberships_membership ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memberships_membership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: readings_reading; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.readings_reading (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    value double precision NOT NULL,
    created_at timestamp with time zone NOT NULL,
    sensor_id bigint NOT NULL
);


ALTER TABLE public.readings_reading OWNER TO invernadero;

--
-- Name: readings_reading_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.readings_reading ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.readings_reading_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sensors_device; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.sensors_device (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    key_prefix character varying(8) NOT NULL,
    api_key_hash character varying(128) NOT NULL,
    is_active boolean NOT NULL,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    greenhouse_id bigint NOT NULL
);


ALTER TABLE public.sensors_device OWNER TO invernadero;

--
-- Name: sensors_device_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.sensors_device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensors_device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sensors_sensor; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.sensors_sensor (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    unit character varying(20) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    reading_interval_seconds integer NOT NULL,
    persist_interval_seconds integer,
    persist_deadband double precision,
    config jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    device_id bigint,
    greenhouse_id bigint NOT NULL,
    zone_id bigint,
    sensor_type_id bigint NOT NULL,
    CONSTRAINT sensors_sensor_persist_interval_seconds_check CHECK ((persist_interval_seconds >= 0)),
    CONSTRAINT sensors_sensor_reading_interval_seconds_check CHECK ((reading_interval_seconds >= 0))
);


ALTER TABLE public.sensors_sensor OWNER TO invernadero;

--
-- Name: sensors_sensor_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.sensors_sensor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensors_sensor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sensors_sensortype; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.sensors_sensortype (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    default_unit character varying(20) NOT NULL,
    valid_min double precision,
    valid_max double precision,
    description text NOT NULL,
    greenhouse_id bigint
);


ALTER TABLE public.sensors_sensortype OWNER TO invernadero;

--
-- Name: sensors_sensortype_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.sensors_sensortype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensors_sensortype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.users_user OWNER TO invernadero;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO invernadero;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: invernadero
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO invernadero;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: invernadero
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: actuators_actuator; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.actuators_actuator (id, name, description, is_active, state, config, created_at, updated_at, device_id, greenhouse_id, zone_id, actuator_type_id) FROM stdin;
\.


--
-- Data for Name: actuators_actuatorstatehistory; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.actuators_actuatorstatehistory (id, state, source, changed_at, actuator_id, changed_by_id) FROM stdin;
\.


--
-- Data for Name: actuators_actuatortype; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.actuators_actuatortype (id, code, name, description, greenhouse_id) FROM stdin;
1	fan	Ventilador		\N
2	ox	oxigeno_bomba	Ventilador de extracción	\N
3	NIKE	Ventilador	Ventilador de extracción	\N
4	fEn	Ventilador	Ventilador de extracción	\N
5	cooler	Enfriador	Enfriamiento evaporativo o refrigeración.	\N
7	valve	Válvula	Apertura/cierre de una línea de riego o gas.	\N
9	curtain	Cortina/malla	Cortina de sombreo o ventilación cenital.	\N
10	mister	Nebulizador	Nebulización/fogging para humedad.	\N
11	xd	ventilador	xd	\N
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add greenhouse	7	add_greenhouse
26	Can change greenhouse	7	change_greenhouse
27	Can delete greenhouse	7	delete_greenhouse
28	Can view greenhouse	7	view_greenhouse
29	Can add zone	8	add_zone
30	Can change zone	8	change_zone
31	Can delete zone	8	delete_zone
32	Can view zone	8	view_zone
33	Can add sensor type	11	add_sensortype
34	Can change sensor type	11	change_sensortype
35	Can delete sensor type	11	delete_sensortype
36	Can view sensor type	11	view_sensortype
37	Can add device	9	add_device
38	Can change device	9	change_device
39	Can delete device	9	delete_device
40	Can view device	9	view_device
41	Can add sensor	10	add_sensor
42	Can change sensor	10	change_sensor
43	Can delete sensor	10	delete_sensor
44	Can view sensor	10	view_sensor
45	Can add reading	12	add_reading
46	Can change reading	12	change_reading
47	Can delete reading	12	delete_reading
48	Can view reading	12	view_reading
49	Can add actuator type	15	add_actuatortype
50	Can change actuator type	15	change_actuatortype
51	Can delete actuator type	15	delete_actuatortype
52	Can view actuator type	15	view_actuatortype
53	Can add actuator	13	add_actuator
54	Can change actuator	13	change_actuator
55	Can delete actuator	13	delete_actuator
56	Can view actuator	13	view_actuator
57	Can add actuator state history	14	add_actuatorstatehistory
58	Can change actuator state history	14	change_actuatorstatehistory
59	Can delete actuator state history	14	delete_actuatorstatehistory
60	Can view actuator state history	14	view_actuatorstatehistory
61	Can add membership	16	add_membership
62	Can change membership	16	change_membership
63	Can delete membership	16	delete_membership
64	Can view membership	16	view_membership
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-09-23 12:31:01.956052+00	1	Invernadero Principal	1	[{"added": {}}]	7	1
2	2026-09-23 12:31:57.412525+00	1	Ventilador	1	[{"added": {}}]	15	1
3	2026-09-23 12:33:06.940794+00	1	Ventilador principal (OFF)	1	[{"added": {}}]	13	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	users	user
7	greenhouses	greenhouse
8	greenhouses	zone
9	sensors	device
10	sensors	sensor
11	sensors	sensortype
12	readings	reading
13	actuators	actuator
14	actuators	actuatorstatehistory
15	actuators	actuatortype
16	memberships	membership
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-23 12:17:15.07235+00
2	contenttypes	0002_remove_content_type_name	2026-09-23 12:17:15.079705+00
3	auth	0001_initial	2026-09-23 12:17:15.106986+00
4	auth	0002_alter_permission_name_max_length	2026-09-23 12:17:15.112972+00
5	auth	0003_alter_user_email_max_length	2026-09-23 12:17:15.118849+00
6	auth	0004_alter_user_username_opts	2026-09-23 12:17:15.124585+00
7	auth	0005_alter_user_last_login_null	2026-09-23 12:17:15.130124+00
8	auth	0006_require_contenttypes_0002	2026-09-23 12:17:15.132574+00
9	auth	0007_alter_validators_add_error_messages	2026-09-23 12:17:15.139668+00
10	auth	0008_alter_user_username_max_length	2026-09-23 12:17:15.145186+00
11	auth	0009_alter_user_last_name_max_length	2026-09-23 12:17:15.150738+00
12	auth	0010_alter_group_name_max_length	2026-09-23 12:17:15.158436+00
13	auth	0011_update_proxy_permissions	2026-09-23 12:17:15.163609+00
14	auth	0012_alter_user_first_name_max_length	2026-09-23 12:17:15.169406+00
15	users	0001_initial	2026-09-23 12:17:15.200168+00
16	greenhouses	0001_initial	2026-09-23 12:17:15.214347+00
17	sensors	0001_initial	2026-09-23 12:17:15.244611+00
18	actuators	0001_initial	2026-09-23 12:17:15.273755+00
19	actuators	0002_initial	2026-09-23 12:17:15.305976+00
20	admin	0001_initial	2026-09-23 12:17:15.325741+00
21	admin	0002_logentry_remove_auto_add	2026-09-23 12:17:15.33324+00
22	admin	0003_logentry_add_action_flag_choices	2026-09-23 12:17:15.342852+00
23	readings	0001_initial	2026-09-23 12:17:15.364125+00
24	sessions	0001_initial	2026-09-23 12:17:15.375008+00
25	memberships	0001_initial	2026-09-26 17:36:37.130462+00
26	actuators	0003_actuatortype_greenhouse_alter_actuatortype_code_and_more	2026-09-30 22:00:44.047113+00
27	sensors	0002_sensortype_greenhouse_alter_sensortype_code_and_more	2026-09-30 22:00:44.090559+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ioqe7e0m6xv9666qwgqqdar0wy4lgn4j	.eJxVjMsOwiAQRf-FtSFMebt07zcQGAapGkhKuzL-uzbpQrf3nHNfLMRtrWEbtIQ5szMDdvrdUsQHtR3ke2y3zrG3dZkT3xV-0MGvPdPzcrh_BzWO-q21KlEjeO8SqslY48AIDwQi5SiUyiSJQGK2xYIFrf2UZCEoGpOX6Nj7A9AvN6c:1x9M6q:xR-ji8QoiXfIZBORQpOKrQBELG11qzDLI78P2c6KDkE	2026-10-07 12:30:00.603682+00
j7h8kzlrjnfip99sd3u1b3f5cfm72ci3	.eJxVjMsOwiAQRf-FtSFMebt07zcQGAapGkhKuzL-uzbpQrf3nHNfLMRtrWEbtIQ5szMDdvrdUsQHtR3ke2y3zrG3dZkT3xV-0MGvPdPzcrh_BzWO-q21KlEjeO8SqslY48AIDwQi5SiUyiSJQGK2xYIFrf2UZCEoGpOX6Nj7A9AvN6c:1xCFHC:Zb8waELiMqyvxcsNqQUtrKGWHdXrFh24q8YQZLoszG8	2026-10-15 11:48:38.063802+00
\.


--
-- Data for Name: greenhouses_greenhouse; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.greenhouses_greenhouse (id, name, description, timezone, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: greenhouses_zone; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.greenhouses_zone (id, name, description, created_at, greenhouse_id) FROM stdin;
\.


--
-- Data for Name: memberships_membership; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.memberships_membership (id, role, created_at, greenhouse_id, user_id) FROM stdin;
\.


--
-- Data for Name: readings_reading; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.readings_reading (id, "timestamp", value, created_at, sensor_id) FROM stdin;
\.


--
-- Data for Name: sensors_device; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.sensors_device (id, name, key_prefix, api_key_hash, is_active, last_seen_at, created_at, greenhouse_id) FROM stdin;
\.


--
-- Data for Name: sensors_sensor; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.sensors_sensor (id, name, unit, description, is_active, reading_interval_seconds, persist_interval_seconds, persist_deadband, config, created_at, updated_at, device_id, greenhouse_id, zone_id, sensor_type_id) FROM stdin;
\.


--
-- Data for Name: sensors_sensortype; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.sensors_sensortype (id, code, name, default_unit, valid_min, valid_max, description, greenhouse_id) FROM stdin;
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1500000$pyonCrcaOno7XJpYYcvcR7$zEyBeUMtJynEVY4BI4xpCd8bfk5z7gZN5QxkAqeLGUE=	\N	f	cliente1				f	t	2026-09-26 17:33:51.932909+00
3	pbkdf2_sha256$1500000$NxeRZCKf2Q7zEPoo3Qvt6N$2Tr+PBasBts5pYNGDiks/GwkTKCBScayCQH9e3IJC4M=	\N	f	usuario_nuevo_1790634389			usuario_nuevo_1790634389@ejemplo.com	f	t	2026-09-28 22:26:29.239805+00
4	pbkdf2_sha256$1500000$J4kjbWwqodB8Z9nFl81ryu$KPJxyeUeCGvYoYiJ/Z3wT3yHtiw5vN1L2GRnI2uzv7g=	\N	f	admin				f	t	2026-09-28 22:27:00.469161+00
5	pbkdf2_sha256$1500000$9vMmIwUNXYr8jHENL9jRKJ$U3nhPljBom1FDxk8EKxkkWXbQDrgzOrX4G80ixAPXTc=	\N	f	jesus1790635279			puenteelizondo021790635279@gmail.com	f	t	2026-09-28 22:41:18.833005+00
6	pbkdf2_sha256$1500000$VVSFvyhrLuCHXBKWNGqbXU$NU7/+1ekaHv0FqK2Cq1H50i/tEY5I+K0ZfQzF2/ixU8=	\N	f	jesus123			jesuspuente112@gmail.com	f	t	2026-09-28 22:42:15.987916+00
7	pbkdf2_sha256$1500000$lGIVNluPTx3D0MWoX8EWJT$M4zlZ43kJSIFkaDCdW6388kov5Lcguhqs1wggS6HL6Y=	2026-09-30 22:03:46.989737+00	f	jesus1234567				f	t	2026-09-30 21:39:51.558367+00
8	pbkdf2_sha256$1500000$DluPeAhnyCpz9ho0I3KXRP$C7loAPGEATAC6gksSJiyNCBMUWIuZZOj40YJhCYJmOw=	2026-09-30 22:04:41.339681+00	f	juanito				f	t	2026-09-30 22:04:34.557647+00
1	pbkdf2_sha256$1500000$fUE9x9bnQutQD9zhvS1uzb$5nerQ40XrK9INqhcAVgMtwulaPAq5JGEQ7af5yab4hU=	2026-10-01 11:48:38.055263+00	t	jesus			puenteelizondo02@gmail.com	t	t	2026-09-23 12:18:14.584739+00
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: invernadero
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: actuators_actuator_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.actuators_actuator_id_seq', 13, true);


--
-- Name: actuators_actuatorstatehistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.actuators_actuatorstatehistory_id_seq', 49, true);


--
-- Name: actuators_actuatortype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.actuators_actuatortype_id_seq', 11, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 3, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: greenhouses_greenhouse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.greenhouses_greenhouse_id_seq', 44, true);


--
-- Name: greenhouses_zone_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.greenhouses_zone_id_seq', 1, false);


--
-- Name: memberships_membership_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.memberships_membership_id_seq', 43, true);


--
-- Name: readings_reading_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.readings_reading_id_seq', 300363, true);


--
-- Name: sensors_device_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.sensors_device_id_seq', 9, true);


--
-- Name: sensors_sensor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.sensors_sensor_id_seq', 24, true);


--
-- Name: sensors_sensortype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.sensors_sensortype_id_seq', 21, true);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.users_user_id_seq', 8, true);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: invernadero
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: actuators_actuator actuators_actuator_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuator
    ADD CONSTRAINT actuators_actuator_pkey PRIMARY KEY (id);


--
-- Name: actuators_actuatorstatehistory actuators_actuatorstatehistory_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuatorstatehistory
    ADD CONSTRAINT actuators_actuatorstatehistory_pkey PRIMARY KEY (id);


--
-- Name: actuators_actuatortype actuators_actuatortype_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuatortype
    ADD CONSTRAINT actuators_actuatortype_pkey PRIMARY KEY (id);


--
-- Name: actuators_actuatortype actuatortype_code_unique_per_greenhouse; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuatortype
    ADD CONSTRAINT actuatortype_code_unique_per_greenhouse UNIQUE (greenhouse_id, code);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: greenhouses_greenhouse greenhouses_greenhouse_name_key; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.greenhouses_greenhouse
    ADD CONSTRAINT greenhouses_greenhouse_name_key UNIQUE (name);


--
-- Name: greenhouses_greenhouse greenhouses_greenhouse_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.greenhouses_greenhouse
    ADD CONSTRAINT greenhouses_greenhouse_pkey PRIMARY KEY (id);


--
-- Name: greenhouses_zone greenhouses_zone_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.greenhouses_zone
    ADD CONSTRAINT greenhouses_zone_pkey PRIMARY KEY (id);


--
-- Name: memberships_membership memberships_membership_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.memberships_membership
    ADD CONSTRAINT memberships_membership_pkey PRIMARY KEY (id);


--
-- Name: readings_reading readings_reading_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.readings_reading
    ADD CONSTRAINT readings_reading_pkey PRIMARY KEY (id);


--
-- Name: sensors_device sensors_device_key_prefix_key; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_device
    ADD CONSTRAINT sensors_device_key_prefix_key UNIQUE (key_prefix);


--
-- Name: sensors_device sensors_device_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_device
    ADD CONSTRAINT sensors_device_pkey PRIMARY KEY (id);


--
-- Name: sensors_sensor sensors_sensor_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_sensor
    ADD CONSTRAINT sensors_sensor_pkey PRIMARY KEY (id);


--
-- Name: sensors_sensortype sensors_sensortype_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_sensortype
    ADD CONSTRAINT sensors_sensortype_pkey PRIMARY KEY (id);


--
-- Name: sensors_sensortype sensortype_code_unique_per_greenhouse; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_sensortype
    ADD CONSTRAINT sensortype_code_unique_per_greenhouse UNIQUE (greenhouse_id, code);


--
-- Name: memberships_membership unique_membership_user_greenhouse; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.memberships_membership
    ADD CONSTRAINT unique_membership_user_greenhouse UNIQUE (user_id, greenhouse_id);


--
-- Name: readings_reading unique_reading_per_sensor_timestamp; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.readings_reading
    ADD CONSTRAINT unique_reading_per_sensor_timestamp UNIQUE (sensor_id, "timestamp");


--
-- Name: greenhouses_zone unique_zone_name_per_greenhouse; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.greenhouses_zone
    ADD CONSTRAINT unique_zone_name_per_greenhouse UNIQUE (greenhouse_id, name);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: actuator_hist_idx; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuator_hist_idx ON public.actuators_actuatorstatehistory USING btree (actuator_id, changed_at DESC);


--
-- Name: actuators_actuator_actuator_type_id_15e002ba; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuator_actuator_type_id_15e002ba ON public.actuators_actuator USING btree (actuator_type_id);


--
-- Name: actuators_actuator_device_id_de4ac796; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuator_device_id_de4ac796 ON public.actuators_actuator USING btree (device_id);


--
-- Name: actuators_actuator_greenhouse_id_2f701927; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuator_greenhouse_id_2f701927 ON public.actuators_actuator USING btree (greenhouse_id);


--
-- Name: actuators_actuator_zone_id_89c8a62b; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuator_zone_id_89c8a62b ON public.actuators_actuator USING btree (zone_id);


--
-- Name: actuators_actuatorstatehistory_actuator_id_d53db5c3; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuatorstatehistory_actuator_id_d53db5c3 ON public.actuators_actuatorstatehistory USING btree (actuator_id);


--
-- Name: actuators_actuatorstatehistory_changed_by_id_15474d10; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuatorstatehistory_changed_by_id_15474d10 ON public.actuators_actuatorstatehistory USING btree (changed_by_id);


--
-- Name: actuators_actuatortype_code_badea4ca; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuatortype_code_badea4ca ON public.actuators_actuatortype USING btree (code);


--
-- Name: actuators_actuatortype_code_badea4ca_like; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuatortype_code_badea4ca_like ON public.actuators_actuatortype USING btree (code varchar_pattern_ops);


--
-- Name: actuators_actuatortype_greenhouse_id_66a7f6e7; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX actuators_actuatortype_greenhouse_id_66a7f6e7 ON public.actuators_actuatortype USING btree (greenhouse_id);


--
-- Name: actuatortype_code_unique_global; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE UNIQUE INDEX actuatortype_code_unique_global ON public.actuators_actuatortype USING btree (code) WHERE (greenhouse_id IS NULL);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: greenhouses_greenhouse_name_65df2cae_like; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX greenhouses_greenhouse_name_65df2cae_like ON public.greenhouses_greenhouse USING btree (name varchar_pattern_ops);


--
-- Name: greenhouses_zone_greenhouse_id_31c8e018; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX greenhouses_zone_greenhouse_id_31c8e018 ON public.greenhouses_zone USING btree (greenhouse_id);


--
-- Name: memberships_membership_greenhouse_id_14c801d7; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX memberships_membership_greenhouse_id_14c801d7 ON public.memberships_membership USING btree (greenhouse_id);


--
-- Name: memberships_membership_user_id_1de5976a; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX memberships_membership_user_id_1de5976a ON public.memberships_membership USING btree (user_id);


--
-- Name: reading_sensor_ts_idx; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX reading_sensor_ts_idx ON public.readings_reading USING btree (sensor_id, "timestamp" DESC);


--
-- Name: readings_reading_sensor_id_84146f5d; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX readings_reading_sensor_id_84146f5d ON public.readings_reading USING btree (sensor_id);


--
-- Name: sensors_device_greenhouse_id_f9dedd7f; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_device_greenhouse_id_f9dedd7f ON public.sensors_device USING btree (greenhouse_id);


--
-- Name: sensors_device_key_prefix_6c32fc87_like; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_device_key_prefix_6c32fc87_like ON public.sensors_device USING btree (key_prefix varchar_pattern_ops);


--
-- Name: sensors_sensor_device_id_74416af8; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_sensor_device_id_74416af8 ON public.sensors_sensor USING btree (device_id);


--
-- Name: sensors_sensor_greenhouse_id_dfc929bf; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_sensor_greenhouse_id_dfc929bf ON public.sensors_sensor USING btree (greenhouse_id);


--
-- Name: sensors_sensor_sensor_type_id_7c0ef1ec; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_sensor_sensor_type_id_7c0ef1ec ON public.sensors_sensor USING btree (sensor_type_id);


--
-- Name: sensors_sensor_zone_id_2d917fd6; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_sensor_zone_id_2d917fd6 ON public.sensors_sensor USING btree (zone_id);


--
-- Name: sensors_sensortype_code_7d58bb3d; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_sensortype_code_7d58bb3d ON public.sensors_sensortype USING btree (code);


--
-- Name: sensors_sensortype_code_7d58bb3d_like; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_sensortype_code_7d58bb3d_like ON public.sensors_sensortype USING btree (code varchar_pattern_ops);


--
-- Name: sensors_sensortype_greenhouse_id_ff882d99; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX sensors_sensortype_greenhouse_id_ff882d99 ON public.sensors_sensortype USING btree (greenhouse_id);


--
-- Name: sensortype_code_unique_global; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE UNIQUE INDEX sensortype_code_unique_global ON public.sensors_sensortype USING btree (code) WHERE (greenhouse_id IS NULL);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: invernadero
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: actuators_actuator actuators_actuator_actuator_type_id_15e002ba_fk_actuators; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuator
    ADD CONSTRAINT actuators_actuator_actuator_type_id_15e002ba_fk_actuators FOREIGN KEY (actuator_type_id) REFERENCES public.actuators_actuatortype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: actuators_actuator actuators_actuator_device_id_de4ac796_fk_sensors_device_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuator
    ADD CONSTRAINT actuators_actuator_device_id_de4ac796_fk_sensors_device_id FOREIGN KEY (device_id) REFERENCES public.sensors_device(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: actuators_actuator actuators_actuator_greenhouse_id_2f701927_fk_greenhous; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuator
    ADD CONSTRAINT actuators_actuator_greenhouse_id_2f701927_fk_greenhous FOREIGN KEY (greenhouse_id) REFERENCES public.greenhouses_greenhouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: actuators_actuator actuators_actuator_zone_id_89c8a62b_fk_greenhouses_zone_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuator
    ADD CONSTRAINT actuators_actuator_zone_id_89c8a62b_fk_greenhouses_zone_id FOREIGN KEY (zone_id) REFERENCES public.greenhouses_zone(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: actuators_actuatorstatehistory actuators_actuatorst_actuator_id_d53db5c3_fk_actuators; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuatorstatehistory
    ADD CONSTRAINT actuators_actuatorst_actuator_id_d53db5c3_fk_actuators FOREIGN KEY (actuator_id) REFERENCES public.actuators_actuator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: actuators_actuatorstatehistory actuators_actuatorst_changed_by_id_15474d10_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuatorstatehistory
    ADD CONSTRAINT actuators_actuatorst_changed_by_id_15474d10_fk_users_use FOREIGN KEY (changed_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: actuators_actuatortype actuators_actuatorty_greenhouse_id_66a7f6e7_fk_greenhous; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.actuators_actuatortype
    ADD CONSTRAINT actuators_actuatorty_greenhouse_id_66a7f6e7_fk_greenhous FOREIGN KEY (greenhouse_id) REFERENCES public.greenhouses_greenhouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: greenhouses_zone greenhouses_zone_greenhouse_id_31c8e018_fk_greenhous; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.greenhouses_zone
    ADD CONSTRAINT greenhouses_zone_greenhouse_id_31c8e018_fk_greenhous FOREIGN KEY (greenhouse_id) REFERENCES public.greenhouses_greenhouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: memberships_membership memberships_membersh_greenhouse_id_14c801d7_fk_greenhous; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.memberships_membership
    ADD CONSTRAINT memberships_membersh_greenhouse_id_14c801d7_fk_greenhous FOREIGN KEY (greenhouse_id) REFERENCES public.greenhouses_greenhouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: memberships_membership memberships_membership_user_id_1de5976a_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.memberships_membership
    ADD CONSTRAINT memberships_membership_user_id_1de5976a_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: readings_reading readings_reading_sensor_id_84146f5d_fk_sensors_sensor_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.readings_reading
    ADD CONSTRAINT readings_reading_sensor_id_84146f5d_fk_sensors_sensor_id FOREIGN KEY (sensor_id) REFERENCES public.sensors_sensor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sensors_device sensors_device_greenhouse_id_f9dedd7f_fk_greenhous; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_device
    ADD CONSTRAINT sensors_device_greenhouse_id_f9dedd7f_fk_greenhous FOREIGN KEY (greenhouse_id) REFERENCES public.greenhouses_greenhouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sensors_sensor sensors_sensor_device_id_74416af8_fk_sensors_device_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_sensor
    ADD CONSTRAINT sensors_sensor_device_id_74416af8_fk_sensors_device_id FOREIGN KEY (device_id) REFERENCES public.sensors_device(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sensors_sensor sensors_sensor_greenhouse_id_dfc929bf_fk_greenhous; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_sensor
    ADD CONSTRAINT sensors_sensor_greenhouse_id_dfc929bf_fk_greenhous FOREIGN KEY (greenhouse_id) REFERENCES public.greenhouses_greenhouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sensors_sensor sensors_sensor_sensor_type_id_7c0ef1ec_fk_sensors_sensortype_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_sensor
    ADD CONSTRAINT sensors_sensor_sensor_type_id_7c0ef1ec_fk_sensors_sensortype_id FOREIGN KEY (sensor_type_id) REFERENCES public.sensors_sensortype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sensors_sensor sensors_sensor_zone_id_2d917fd6_fk_greenhouses_zone_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_sensor
    ADD CONSTRAINT sensors_sensor_zone_id_2d917fd6_fk_greenhouses_zone_id FOREIGN KEY (zone_id) REFERENCES public.greenhouses_zone(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sensors_sensortype sensors_sensortype_greenhouse_id_ff882d99_fk_greenhous; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.sensors_sensortype
    ADD CONSTRAINT sensors_sensortype_greenhouse_id_ff882d99_fk_greenhous FOREIGN KEY (greenhouse_id) REFERENCES public.greenhouses_greenhouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: invernadero
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict k5Enqu4KJgkXm7p9RU1NhmhGI8aoMTRig5rw8U3CwMtsyPp2GgKbNvUIKl5hjXE

