# Generated by Django 5.2.17 on 2026-10-06 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actuators", "0003_actuatortype_greenhouse_alter_actuatortype_code_and_more"),
        ("greenhouses", "0001_initial"),
        ("sensors", "0002_sensortype_greenhouse_alter_sensortype_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlLoop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("off", "Apagado"),
                            ("on_off", "On/Off"),
                            ("p", "P"),
                            ("pi", "PI"),
                            ("pid", "PID"),
                        ],
                        default="off",
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("direct", "Directa (la salida sube la variable)"),
                            ("reverse", "Inversa (la salida baja la variable)"),
                        ],
                        default="direct",
                        max_length=10,
                    ),
                ),
                ("setpoint", models.FloatField()),
                (
                    "hysteresis",
                    models.FloatField(default=0.5, help_text="Solo On/Off."),
                ),
                ("kp", models.FloatField(default=1.0)),
                ("ki", models.FloatField(default=0.0)),
                ("kd", models.FloatField(default=0.0)),
                ("output_min", models.FloatField(default=0.0)),
                ("output_max", models.FloatField(default=100.0)),
                (
                    "integral_limit",
                    models.FloatField(
                        default=100.0,
                        help_text="Límite del término integral (anti-windup), en unidades de salida.",
                    ),
                ),
                ("sample_time_ms", models.PositiveIntegerField(default=1000)),
                ("enabled", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_version", models.PositiveIntegerField(default=0)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actuator",
                    models.ForeignKey(
                        help_text="Salida que maneja el controlador.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_loops",
                        to="actuators.actuator",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Dispositivo que ejecuta el lazo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_loops",
                        to="sensors.device",
                    ),
                ),
                (
                    "greenhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_loops",
                        to="greenhouses.greenhouse",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        help_text="Variable de proceso (PV) que el controlador lee.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_loops",
                        to="sensors.sensor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["greenhouse", "name"],
            },
        ),
        migrations.CreateModel(
            name="ControlLoopChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("changes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="control.controlloop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="controlloop",
            constraint=models.UniqueConstraint(
                fields=("actuator",), name="controlloop_one_per_actuator"
            ),
        ),
        migrations.AddConstraint(
            model_name="controlloop",
            constraint=models.CheckConstraint(
                condition=models.Q(("output_min__lt", models.F("output_max"))),
                name="controlloop_output_range",
            ),
        ),
        migrations.AddIndex(
            model_name="controlloopchange",
            index=models.Index(
                fields=["loop", "-created_at"], name="ctrlchange_loop_idx"
            ),
        ),
    ]
