# Generated by Django 5.2.17 on 2026-10-06 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actuators", "0003_actuatortype_greenhouse_alter_actuatortype_code_and_more"),
        ("control", "0001_initial"),
        ("sensors", "0002_sensortype_greenhouse_alter_sensortype_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlloop",
            name="actuator",
            field=models.ForeignKey(
                help_text="Salida que maneja el controlador.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control_loops",
                to="actuators.actuator",
            ),
        ),
        migrations.AlterField(
            model_name="controlloop",
            name="device",
            field=models.ForeignKey(
                help_text="Dispositivo que ejecuta el lazo.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control_loops",
                to="sensors.device",
            ),
        ),
        migrations.AlterField(
            model_name="controlloop",
            name="sensor",
            field=models.ForeignKey(
                help_text="Variable de proceso (PV) que el controlador lee.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control_loops",
                to="sensors.sensor",
            ),
        ),
    ]
