# Generated by Django 6.1.1 on 2026-09-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouses', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Ej: 'fan'", unique=True)),
                ('name', models.CharField(help_text="Ej: 'Ventilador'", max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='Dispositivo físico que controla este actuador (puede ser el mismo que reporta sensores, ej. un relé en el mismo ESP32).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuators', to='sensors.device')),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actuators', to='greenhouses.greenhouse')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuators', to='greenhouses.zone')),
            ],
            options={
                'ordering': ['greenhouse', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActuatorStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automation', 'Automatización')], default='manual', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_history', to='actuators.actuator')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
