# Generated by Django 6.1.1 on 2026-09-23 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actuators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actuatorstatehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuator_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actuator',
            name='actuator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actuators', to='actuators.actuatortype'),
        ),
        migrations.AddIndex(
            model_name='actuatorstatehistory',
            index=models.Index(fields=['actuator', '-changed_at'], name='actuator_hist_idx'),
        ),
    ]
