# Generated by Django 6.1.1 on 2026-09-30 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actuators", "0002_initial"),
        ("greenhouses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actuatortype",
            name="greenhouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío = tipo global. Con invernadero = solo visible para ese invernadero.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actuator_types",
                to="greenhouses.greenhouse",
            ),
        ),
        migrations.AlterField(
            model_name="actuatortype",
            name="code",
            field=models.SlugField(help_text="Ej: 'fan'"),
        ),
        migrations.AddConstraint(
            model_name="actuatortype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("greenhouse__isnull", True)),
                fields=("code",),
                name="actuatortype_code_unique_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="actuatortype",
            constraint=models.UniqueConstraint(
                fields=("greenhouse", "code"),
                name="actuatortype_code_unique_per_greenhouse",
            ),
        ),
    ]
